const orderLineItemsData = [
  {
    id: 1,
    quantity: 2,
    price: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    product_id: 1,
    order_id: 1,
  },
  {
    id: 2,
    quantity: 2,
    price: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    product_id: 2,
    order_id: 2,
  },
  {
    id: 3,
    quantity: 2,
    price: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    product_id: 3,
    order_id: 3,
  },
  {
    id: 4,
    quantity: 2,
    price: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    product_id: 4,
    order_id: 4,
  },
  {
    id: 5,
    quantity: 2,
    price: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    product_id: 5,
    order_id: 5,
  },
  {
    id: 6,
    quantity: 2,
    price: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    product_id: 6,
    order_id: 6,
  },
];

module.exports = orderLineItemsData;
